version: '2'

services:
  db:
    privileged: true
    image: postgres:10.0
    networks:
      - icw-backend
    ports:
      - 5432:5432
    volumes:
      - mongo-data:/data/db
    environment:
      - POSTGRES_USER=icw
      - POSTGRES_PASSWORD=icw
  web:
    privileged: true
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./server:/server
      - ./client/dist:/template
    environment:
      - FLASK_JWT_KEY=Ywupby0uOsIUENVboiQnqIfZS2IGMCEP
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - POSTGRES_PORT=5432
      - POSTGRES_USER=icw
      - POSTGRES_PASSWORD=icw
    command:
      flask run --host=0.0.0.0 --port=5000
    networks:
      - icw-backend
    depends_on:
      - db

networks:
  icw-backend:
    driver: bridge

volumes:
  mongo-data: # to persist data, virtualbox file sync driver won't work with MongoDB engine on Windows & Mac
